name: flutter_record
description: Audio recorder from microphone to a given file path with multiple codecs, bit rate and sampling rate options.
version: 3.1.0
homepage: https://github.com/josephcrowell/flutter_record/

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=2.0.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_record_platform_interface: 0.2.0
  flutter_record_web: 0.2.1

dependency_overrides:
  flutter_record_platform_interface:
    path: flutter_record_platform_interface
  flutter_record_web:
    path: flutter_record_web

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.josephcrowell.flutter_record
        pluginClass: FlutterRecordPlugin
      ios:
        pluginClass: FlutterRecordPlugin
      web:
        default_package: flutter_record_web
