name: flutter_record_web
description: Flutter Record web implementation.
version: 0.2.1
homepage: https://github.com/josephcrowell/flutter_record/tree/master/flutter_record_web

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_record_platform_interface:
    git:
      url: https://github.com/josephcrowell/flutter_record.git
      path: flutter_record_platform_interface

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterRecordPluginWeb
        fileName: "flutter_record_web.dart"
